### PR TITLE
#33 add Play 2.6 compatibility & Scala 2.12

### PR DESCRIPTION
**Pull request by dgouyette**
A first testing/compiling version.
I removed Xor cats.
Replaced  import `play.api.libs.concurrent.Execution.Implicits.defaultContext` with   `scala.concurrent.ExecutionContext.Implicits.global`

### CODE REVIEW

**Comment by vil1** [comment]
I'm not sure I wan't to get `scalaVersion := "2.12.2"` straight in.
I'd like to continue with publishing 2.11 artifacts, at least for the next few months. so I think cross-compilation would be more appropriate

**Comment by dgouyette** [comment]
Ok, I will see if all the libraries used were cross compiled too

**Comment by vil1** [comment]
Interestingly/annoyingly this makes the tests coverage decrease…

**Comment by dgouyette** [comment]
I removed some tests that have become useless

**Comment by vil1** [comment]
Not so useless apparently ^^
I noticed that our typeclasses instances (for cats and scalaz) never had any discipline enforced (shame on me), although laws are enforced on `Step` directly.
Would you mind if I fix that before merging this PR ? I might not have the time to do so before next week though.

**Comment by dgouyette** [comment]
Of course.
I keep testing a local version for my own usages

**Comment by adamsar** [comment]
Guys is there any progress on this? I'm writing the monad laws tests in a branch myself, have some trouble compiling with the specs2/discipline combination.

**Comment by vil1** [comment]
I'm currently on vacation without any laptop, so there is no progress on my side. 
I'll get back home next week and have a look.

**Comment by adamsar** [comment]
Ah no worries then, I'll keep forging ahead and try to get you a PR

**Comment by vil1** [comment]
Closing this after #36

**Comment by dgouyette** [comment]
👍

**Pull request closed without merging**
