### PR TITLE
Learn to promote XorT[Future, B, A] and OptionT[Future, A] to Step

### PR DESCRIPTION
**Pull request by aeons**
Add support for XorT[Future, B, A] and OptionT[Future, A].

### CODE REVIEW

**Comment by vil1** [comment]
Hi, 

I like the idea and this looks good. Would you mind adding these new promotions in the table in README.md (and your name in the contributors section) ?

Having the same promotions in the scalaz world would be nide too, but this can be the purpose of another PR.

Thanks

**Comment by aeons** [comment]
Sure, will take a look at it when I have time

**Comment by aeons** [comment]
I updated the readme.

I agree that the scalaz implementation should be a separate PR.

**Comment by vil1** [comment]
Perfect, lets merge this.

Thanks again !

**Pull request merged**
